exclude: []

layouts_dir: 'node_modules/uptick-demo-site/dist'

package_name: React Bucketed Scheduler
package_github_url: https://github.com/uptick/react-bucketed-scheduler
package_npm_url: https://www.npmjs.com/package/react-bucketed-scheduler
